version: "3"
services:
  backend:
    image: amazoncorretto:21
    platform: linux/x86_64
    container_name: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      GOOGLE_AUTH_CLIENT_ID: ${GOOGLE_AUTH_CLIENT_ID}
      GOOGLE_AUTH_CLIENT_SECRET: ${GOOGLE_AUTH_CLIENT_SECRET}
    command: ./gradlew bootRun
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/actuator/health"]
      interval: 1s
      timeout: 3s
      retries: 60

  frontend:
    image: node:latest
    platform: linux/x86_64
    container_name: frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
