spring:
  application:
    name: backend
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_AUTH_CLIENT_ID}
            client-secret: ${GOOGLE_AUTH_CLIENT_SECRET}

logging:
  level:
    org:
    springframework:
      security: debug
